### ISSUE TITLE
development automation

### ISSUE THREAD

**Issue by cfoellmann** [mikeselander/wp-options-editor#15]
I would love to add some task runner like grunt or gulp to do the following:

- [ ] convert readme.txt to MARKDOWN
- [ ] update dependencies (list.js + jquery.jeditables)
- [ ] generate minified version of css and js files

- more!?

Would that be ok for you @mikeselander ? Which one is your favorite?

**Comment by mikeselander** [comment]
Some more automation would be great, but would generally lean towards Webpack as a more future-proof option for builds. The 2 item you've listed would both be useful.

Thanks for all of your help on this!

**Comment by cfoellmann** [comment]
I have not used webpack yet. But I will look into it and see if I can get the workflow going for the two tasks for a start

**Comment by cfoellmann** [comment]
I looked into webpack and I don't have the time to get into it at the moment.
I will set up a grunt or gulp config to run the tasks mentioned above

**Comment by cfoellmann** [comment]
@mikeselander how about you add a project here on the repo? Like `1.2`
So you can group up the stuff you like to add. Then I can work on what you want to include.
