### ISSUE TITLE
Add value type column

### ISSUE THREAD

**Issue by cfoellmann** [mikeselander/wp-options-editor#9]
Add a column "Type".
Detect `string`, `serialized` (, `json` ?) + sorting by type 
______
![type](https://user-images.githubusercontent.com/1256090/33280430-50e73042-d3a2-11e7-9373-4df449528371.png)

**Comment by mikeselander** [comment]
@cfoellmann can you give an example of how this would be really useful? I'm having a hard time seeing the use case but am totally open if I'm missing it.

**Comment by cfoellmann** [comment]
sorting would be a usecase for me

**Comment by cfoellmann** [comment]
close for now. @mikeselander I see your point. It is not as useful as I imagined
